spring.application.name=finance-manager

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/finance_db
spring.datasource.username=postgres
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}

# JPA / Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Server configuration
server.port=8080

# Logging
logging.level.com.syfe.finance_manager=INFO
logging.level.org.springframework.security=WARN
